sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: itMciDk6lwdCTJZkREPCCteG4jVMmZlu5XKyACQXAM7eTw6YD8nHSNfNRjJS8/H4FUyxmVbUOj3lMdRvGZ5qZIsXXoUvlu6f0PRZ1Dj4W1jVjoFT+JlsSYKZJJC+oZ7chXDqMv4b1VBuoVpPrAsioi5oc5EhGxhqVgUyeJokdSpHJEMPIW4xP7uTsW+LFemfxi8LM8sV1cFMFITlza/8AyhcoAgYvJGcFVWgQcfsuNH5Uj1HsCqHQYvKFmCwa/YZqoWdlJtCBsFlJhuGheBqliYvpkzbEzwx66Pi9O196FHejqZT4a4RDW9RCmNhFlR6gw9NWGvUOGijnxivz0GN+DLwZuacSXDZLP3w+ksR+WPQhpxWZrfsU8bnaxVqJ/Kkb5HKdjJ2CuvdF0vSm+QywEZfFtsrr3iaL6T2dpkq7nIUxFRqaMdVmOJgPmYfVcLBOK59PvPfuzDqyPTXKkh0uDQn+22yfrWBCJZbNFnpYvAlsesANlBLvgVZn+BINlFDAr6XdQUgMEIJlgjCMmFthPaOUZEOWmSGHLJI+SDsgI/ZcbDZfGor3a8SwulGzZ2UEMGg0zYU6hO8Dhs9B7Jaesr1vrXGUCdLHc+mDAV05YAqkRlrTdSFhJN62IsLmMzcsIZ1dKPrQBBKylZ6z9qygRjzs4Ldy5/3O+loc6JpPn8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Drama-on-the-Seashore_1427
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy